service: funcionario-crud-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getFuncionario:
    handler: handler.getFuncionario
    events:
     - http:
         path: /funcionario/{id}
         method: get
  getAllFuncionarios:
    handler: handler.getAllFuncionarios
    events:
     - http:
         path: /funcionario/
         method: get
  addFuncionario:
    handler: handler.addFuncionario
    events:
      - http:
          path: /funcionario/
          method: post

plugins:
- serverless-offline